target-version = "py312"
line-length = 120

[lint]
preview = true
select = ["ALL"]
ignore = [
    # I don't care about docs in AoC
    "D",
    # Prints are allowed in AoC
    "T20",
    # Magic values are going to happen in AoC
    "PLR2004",
    # Copyright? xD
    "CPY",
    # Code complexity goes brrr in AoC
    "C901", "PLR0912",
]

[format]
preview = true